### ISSUE TITLE
rownames(beta) does not work for me

### ISSUE THREAD

**Issue by matthiasdusch** [retostauffer/Rfoehnix#5]
Quite likely this is due to my limited R knowledge but for me the following line does not work as `rownames(beta)` always returns `NULL`

https://github.com/retostauffer/Rfoehnix/blob/dc351b8f5ce04a24c7c9a07697c58f19b71dc8bd/R/foehnix_functions.R#L144

minimal working example from the unit test:
```
beta <- structure(matrix(c(2, -5, -5), ncol = 1), rownames = c("(Intercept)", "A", "B"))
ic <- grep("^\\(Intercept\\)$", rownames(beta))
```
as rownames returns NULL, `ic` is subsequently `integer(0)` and the IF-loop after the above quoted line always uses the ELSE fallback.

**Comment by retostauffer** [comment]
The problem is the "`structure(...)`" call. It sets attributes to an object - but an attribute `rownames` does not exist. In _R_ a matrix has an attribute `dimnames`. Thus, the minimal example has to look as follows:

    beta <- structure(matrix(c(2, -5, -5), ncol = 1), dimnames = list(c("(Intercept)", "A", "B"), NULL))
    ic <- grep("^\\(Intercept\\)$", rownames(beta))

We have to set a list containing both, the row and column names (`dimnames = list(<rownames>, <colnames>)`). `NULL` means "no column names in this case". That should work.

**Comment by retostauffer** [comment]
Ah, now I found it! Was wondering where it was :). This test was more than just wrong, adjusted the manual destandardization test, see commit https://github.com/retostauffer/Rfoehnix/commit/1f1f04aa4da395d6bf6562ca8bd50632b385d408 (devel branch).

**Comment by retostauffer** [comment]
I consider this one as closed (see https://github.com/matthiasdusch/foehnix-python/commit/27d9e01aeeb579ae61d063c66fdb96ca37c3f3e8)

**Comment by matthiasdusch** [comment]
looks good to me and I can reproduce the results :+1:
